from __future__ import annotations

ATTR_NORMAL = 0
ATTR_CROSSWALK = 1
ATTR_INTERSECTION = 2
ATTR_ONEWAY = 3
ATTR_HIGHWAY_LEFT = 4
ATTR_HIGHWAY_RIGHT = 5
ATTR_ROUNDABOUT = 6
ATTR_STOPLINE = 7
ATTR_DOTTED = 8
ATTR_DOTTED_CROSSWALK = 9
ATTR_INTERSECTION_EXIT = 11

WAYPOINT_MODE_ATTRS = {
    ATTR_INTERSECTION,
    ATTR_STOPLINE,
    ATTR_INTERSECTION_EXIT,
}

ATTR_ROUTE_WEIGHTS = {
    ATTR_NORMAL: 1.00,
    ATTR_CROSSWALK: 1.08,
    ATTR_INTERSECTION: 1.02,
    ATTR_ONEWAY: 0.98,
    ATTR_HIGHWAY_LEFT: 0.95,
    ATTR_HIGHWAY_RIGHT: 0.95,
    ATTR_ROUNDABOUT: 1.04,
    ATTR_STOPLINE: 1.10,
    ATTR_DOTTED: 1.00,
    ATTR_DOTTED_CROSSWALK: 1.08,
    ATTR_INTERSECTION_EXIT: 1.02,
}

ATTR_NAMES = {
    ATTR_NORMAL: "normal",
    ATTR_CROSSWALK: "crosswalk",
    ATTR_INTERSECTION: "intersection",
    ATTR_ONEWAY: "oneway",
    ATTR_HIGHWAY_LEFT: "hw_left",
    ATTR_HIGHWAY_RIGHT: "hw_right",
    ATTR_ROUNDABOUT: "roundabout",
    ATTR_STOPLINE: "stopline",
    ATTR_DOTTED: "dotted",
    ATTR_DOTTED_CROSSWALK: "dotted_xwalk",
    ATTR_INTERSECTION_EXIT: "intersection_exit",
}
