#!/usr/bin/env python3
"""Analyze a constant-turn run captured by manual_bus_logger.py.

The goal is to answer, per steady steering segment:

* how long the commanded arc lasted,
* what command plateau was actually held,
* whether feedback/pose/yaw signals were present,
* what virtual radius can be inferred from distance + yaw or pose path,
* what kinematic radius would be expected from the configured wheelbase.

This is intentionally notebook-local and works on the CSV generated by
``scripts/manual_bus_logger.py``.
"""

from __future__ import annotations

import argparse
import csv
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Any


def _safe_float(value: Any) -> float | None:
    if value in ("", "None", None):
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _mean(values: list[float]) -> float | None:
    if not values:
        return None
    return sum(values) / len(values)


def _unwrap_deg(values: list[float]) -> list[float]:
    if not values:
        return []
    out = [values[0]]
    offset = 0.0
    prev = values[0]
    for value in values[1:]:
        delta = value - prev
        if delta > 180.0:
            offset -= 360.0
        elif delta < -180.0:
            offset += 360.0
        out.append(value + offset)
        prev = value
    return out


def _path_length(points: list[tuple[float, float]]) -> float | None:
    if len(points) < 2:
        return None
    total = 0.0
    for idx in range(1, len(points)):
        x0, y0 = points[idx - 1]
        x1, y1 = points[idx]
        total += math.hypot(x1 - x0, y1 - y0)
    return total


def _radius_from_arc(arc_length_m: float | None, yaw_delta_deg: float | None) -> float | None:
    if arc_length_m is None or yaw_delta_deg is None:
        return None
    yaw_delta_rad = math.radians(abs(yaw_delta_deg))
    if yaw_delta_rad < 1e-6:
        return None
    return arc_length_m / yaw_delta_rad


def _steer_from_radius_deg(wheelbase_m: float, radius_m: float | None) -> float | None:
    if radius_m is None or abs(radius_m) < 1e-6:
        return None
    return math.degrees(math.atan(float(wheelbase_m) / abs(float(radius_m))))


def _format(value: float | None, digits: int = 3) -> str:
    if value is None:
        return "--"
    return f"{value:.{digits}f}"


@dataclass
class Row:
    elapsed_s: float
    cmd_speed_cms: float | None
    cmd_steer_deg_wire: float | None
    feedback_speed_cms: float | None
    feedback_steer_deg_wire: float | None
    distance_rel_m: float | None
    imu_yaw_deg: float | None
    pose_x_m: float | None
    pose_y_m: float | None
    pose_yaw_deg: float | None


@dataclass
class Segment:
    start_idx: int
    end_idx: int


def _load_rows(csv_path: Path) -> list[Row]:
    rows: list[Row] = []
    with csv_path.open("r", encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        for raw in reader:
            elapsed = _safe_float(raw.get("logger_elapsed_s"))
            if elapsed is None:
                continue
            rows.append(
                Row(
                    elapsed_s=elapsed,
                    cmd_speed_cms=_safe_float(raw.get("cmd_speed_cms")),
                    cmd_steer_deg_wire=_safe_float(raw.get("cmd_steer_deg_wire")),
                    feedback_speed_cms=_safe_float(raw.get("feedback_speed_cms")),
                    feedback_steer_deg_wire=_safe_float(raw.get("feedback_steer_deg_wire")),
                    distance_rel_m=_safe_float(raw.get("distance_rel_m")),
                    imu_yaw_deg=_safe_float(raw.get("imu_yaw_deg")),
                    pose_x_m=_safe_float(raw.get("pose_x_m")),
                    pose_y_m=_safe_float(raw.get("pose_y_m")),
                    pose_yaw_deg=_safe_float(raw.get("pose_yaw_deg")),
                )
            )
    return rows


def _matches_segment(
    row: Row,
    *,
    target_speed_cms: float,
    speed_tol_cms: float,
    target_steer_deg: float,
    steer_tol_deg: float,
) -> bool:
    if row.cmd_speed_cms is None or row.cmd_steer_deg_wire is None:
        return False
    return (
        abs(row.cmd_speed_cms - target_speed_cms) <= speed_tol_cms
        and abs(row.cmd_steer_deg_wire - target_steer_deg) <= steer_tol_deg
    )


def _find_segments(
    rows: list[Row],
    *,
    target_speed_cms: float,
    speed_tol_cms: float,
    target_steer_deg: float,
    steer_tol_deg: float,
    min_duration_s: float,
) -> list[Segment]:
    segments: list[Segment] = []
    start_idx: int | None = None

    for idx, row in enumerate(rows):
        active = _matches_segment(
            row,
            target_speed_cms=target_speed_cms,
            speed_tol_cms=speed_tol_cms,
            target_steer_deg=target_steer_deg,
            steer_tol_deg=steer_tol_deg,
        )
        if active and start_idx is None:
            start_idx = idx
        elif not active and start_idx is not None:
            end_idx = idx - 1
            if rows[end_idx].elapsed_s - rows[start_idx].elapsed_s >= min_duration_s:
                segments.append(Segment(start_idx, end_idx))
            start_idx = None

    if start_idx is not None:
        end_idx = len(rows) - 1
        if rows[end_idx].elapsed_s - rows[start_idx].elapsed_s >= min_duration_s:
            segments.append(Segment(start_idx, end_idx))

    return segments


def _theoretical_radius_m(wheelbase_m: float, steer_deg: float | None) -> float | None:
    if steer_deg is None:
        return None
    steer_rad = math.radians(abs(steer_deg))
    if abs(steer_rad) < 1e-6:
        return None
    return wheelbase_m / math.tan(steer_rad)


def _resolve_csv_path(path_arg: str) -> Path:
    path = Path(path_arg)
    if path.is_dir():
        path = path / "timeseries.csv"
    return path.resolve()


def _analyze_segment(
    rows: list[Row],
    segment: Segment,
    wheelbase_m: float,
    *,
    physical_lap_time_s: float | None = None,
    physical_radius_m: float | None = None,
) -> dict[str, Any]:
    data = rows[segment.start_idx : segment.end_idx + 1]

    cmd_speed_vals = [row.cmd_speed_cms for row in data if row.cmd_speed_cms is not None]
    cmd_steer_vals = [row.cmd_steer_deg_wire for row in data if row.cmd_steer_deg_wire is not None]
    fb_speed_vals = [row.feedback_speed_cms for row in data if row.feedback_speed_cms is not None]
    fb_steer_vals = [row.feedback_steer_deg_wire for row in data if row.feedback_steer_deg_wire is not None]
    distance_vals = [row.distance_rel_m for row in data if row.distance_rel_m is not None]
    imu_yaw_vals = [row.imu_yaw_deg for row in data if row.imu_yaw_deg is not None]
    pose_yaw_vals = [row.pose_yaw_deg for row in data if row.pose_yaw_deg is not None]
    pose_points = [
        (row.pose_x_m, row.pose_y_m)
        for row in data
        if row.pose_x_m is not None and row.pose_y_m is not None
    ]

    imu_yaw_unwrapped = _unwrap_deg(imu_yaw_vals)
    pose_yaw_unwrapped = _unwrap_deg(pose_yaw_vals)

    distance_delta_m = None
    if len(distance_vals) >= 2:
        distance_delta_m = distance_vals[-1] - distance_vals[0]

    imu_yaw_delta_deg = None
    if len(imu_yaw_unwrapped) >= 2:
        imu_yaw_delta_deg = imu_yaw_unwrapped[-1] - imu_yaw_unwrapped[0]

    pose_yaw_delta_deg = None
    if len(pose_yaw_unwrapped) >= 2:
        pose_yaw_delta_deg = pose_yaw_unwrapped[-1] - pose_yaw_unwrapped[0]

    pose_path_length_m = _path_length(
        [(float(x), float(y)) for x, y in pose_points]
    )

    radius_from_distance_pose_yaw = _radius_from_arc(distance_delta_m, pose_yaw_delta_deg)
    radius_from_distance_imu_yaw = _radius_from_arc(distance_delta_m, imu_yaw_delta_deg)
    radius_from_pose_path_pose_yaw = _radius_from_arc(pose_path_length_m, pose_yaw_delta_deg)

    mean_cmd_steer = _mean([float(v) for v in cmd_steer_vals])
    mean_cmd_speed_cms = _mean([float(v) for v in cmd_speed_vals])
    mean_fb_speed_cms = _mean([float(v) for v in fb_speed_vals])
    mean_fb_steer_deg = _mean([float(v) for v in fb_steer_vals])

    physical_radius_from_lap_m = None
    if physical_lap_time_s is not None:
        speed_cms_for_physical = mean_fb_speed_cms if mean_fb_speed_cms is not None else mean_cmd_speed_cms
        if speed_cms_for_physical is not None:
            speed_mps = speed_cms_for_physical / 100.0
            physical_radius_from_lap_m = (speed_mps * float(physical_lap_time_s)) / (2.0 * math.pi)

    return {
        "start_s": data[0].elapsed_s,
        "end_s": data[-1].elapsed_s,
        "duration_s": data[-1].elapsed_s - data[0].elapsed_s,
        "samples": len(data),
        "mean_cmd_speed_cms": mean_cmd_speed_cms,
        "mean_cmd_steer_deg": mean_cmd_steer,
        "mean_fb_speed_cms": mean_fb_speed_cms,
        "mean_fb_steer_deg": mean_fb_steer_deg,
        "distance_delta_m": distance_delta_m,
        "imu_yaw_delta_deg": imu_yaw_delta_deg,
        "pose_yaw_delta_deg": pose_yaw_delta_deg,
        "pose_path_length_m": pose_path_length_m,
        "radius_from_distance_pose_yaw_m": radius_from_distance_pose_yaw,
        "radius_from_distance_imu_yaw_m": radius_from_distance_imu_yaw,
        "radius_from_pose_path_pose_yaw_m": radius_from_pose_path_pose_yaw,
        "theoretical_radius_m": _theoretical_radius_m(wheelbase_m, mean_cmd_steer),
        "effective_steer_from_distance_imu_yaw_deg": _steer_from_radius_deg(
            wheelbase_m, radius_from_distance_imu_yaw
        ),
        "effective_steer_from_distance_pose_yaw_deg": _steer_from_radius_deg(
            wheelbase_m, radius_from_distance_pose_yaw
        ),
        "physical_radius_input_m": physical_radius_m,
        "effective_steer_from_physical_radius_deg": _steer_from_radius_deg(
            wheelbase_m, physical_radius_m
        ),
        "physical_radius_from_lap_m": physical_radius_from_lap_m,
        "effective_steer_from_physical_lap_deg": _steer_from_radius_deg(
            wheelbase_m, physical_radius_from_lap_m
        ),
        "has_feedback_speed": bool(fb_speed_vals),
        "has_feedback_steer": bool(fb_steer_vals),
        "has_imu_yaw": bool(imu_yaw_vals),
        "has_pose": bool(pose_points) and bool(pose_yaw_vals),
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Analyze a constant-turn segment from manual_bus_logger CSV output."
    )
    parser.add_argument(
        "input",
        help="Path to a timeseries.csv file or a run directory containing it.",
    )
    parser.add_argument(
        "--target-steer-deg",
        type=float,
        required=True,
        help="Target commanded steer plateau in wire degrees, e.g. 10 or -10.",
    )
    parser.add_argument(
        "--target-speed-cms",
        type=float,
        default=20.0,
        help="Target commanded speed plateau in cm/s (default: 20).",
    )
    parser.add_argument(
        "--steer-tol-deg",
        type=float,
        default=1.0,
        help="Tolerance around target steer in degrees (default: 1.0).",
    )
    parser.add_argument(
        "--speed-tol-cms",
        type=float,
        default=1.0,
        help="Tolerance around target speed in cm/s (default: 1.0).",
    )
    parser.add_argument(
        "--min-duration-s",
        type=float,
        default=1.0,
        help="Minimum steady-state duration to keep a segment (default: 1.0).",
    )
    parser.add_argument(
        "--wheelbase-m",
        type=float,
        default=0.260,
        help="Wheelbase used for theoretical radius (default: 0.260).",
    )
    parser.add_argument(
        "--physical-lap-time-s",
        type=float,
        default=None,
        help="Optional measured real-world full-lap time in seconds.",
    )
    parser.add_argument(
        "--physical-radius-m",
        type=float,
        default=None,
        help="Optional measured real-world turn radius in meters.",
    )
    args = parser.parse_args()

    csv_path = _resolve_csv_path(args.input)
    if not csv_path.exists():
        raise SystemExit(f"CSV not found: {csv_path}")

    rows = _load_rows(csv_path)
    if not rows:
        raise SystemExit(f"No rows found in {csv_path}")

    segments = _find_segments(
        rows,
        target_speed_cms=float(args.target_speed_cms),
        speed_tol_cms=float(args.speed_tol_cms),
        target_steer_deg=float(args.target_steer_deg),
        steer_tol_deg=float(args.steer_tol_deg),
        min_duration_s=float(args.min_duration_s),
    )

    print(f"[analyze_constant_turn] csv={csv_path}")
    print(
        "[analyze_constant_turn] "
        f"target_speed={args.target_speed_cms:.1f}cm/s "
        f"target_steer={args.target_steer_deg:.1f}deg"
    )

    if not segments:
        print("[analyze_constant_turn] no steady-state segments found")
        return 1

    for idx, segment in enumerate(segments, start=1):
        report = _analyze_segment(
            rows,
            segment,
            float(args.wheelbase_m),
            physical_lap_time_s=args.physical_lap_time_s,
            physical_radius_m=args.physical_radius_m,
        )
        print(
            f"\nSegment {idx}: "
            f"t={report['start_s']:.2f}s..{report['end_s']:.2f}s "
            f"duration={report['duration_s']:.2f}s samples={report['samples']}"
        )
        print(
            "  "
            f"cmd_speed={_format(report['mean_cmd_speed_cms'], 2)}cm/s "
            f"cmd_steer={_format(report['mean_cmd_steer_deg'], 2)}deg "
            f"fb_speed={_format(report['mean_fb_speed_cms'], 2)}cm/s "
            f"fb_steer={_format(report['mean_fb_steer_deg'], 2)}deg"
        )
        print(
            "  "
            f"distance_delta={_format(report['distance_delta_m'], 3)}m "
            f"imu_yaw_delta={_format(report['imu_yaw_delta_deg'], 2)}deg "
            f"pose_yaw_delta={_format(report['pose_yaw_delta_deg'], 2)}deg"
        )
        print(
            "  "
            f"pose_path_length={_format(report['pose_path_length_m'], 3)}m "
            f"radius(distance+poseYaw)={_format(report['radius_from_distance_pose_yaw_m'], 3)}m "
            f"radius(distance+imuYaw)={_format(report['radius_from_distance_imu_yaw_m'], 3)}m "
            f"radius(posePath+poseYaw)={_format(report['radius_from_pose_path_pose_yaw_m'], 3)}m"
        )
        print(
            "  "
            f"theoretical_radius={_format(report['theoretical_radius_m'], 3)}m "
            f"effective_steer(imu)={_format(report['effective_steer_from_distance_imu_yaw_deg'], 2)}deg "
            f"effective_steer(pose)={_format(report['effective_steer_from_distance_pose_yaw_deg'], 2)}deg"
        )
        print(
            "  "
            f"physical_radius(input)={_format(report['physical_radius_input_m'], 3)}m "
            f"effective_steer(physical_radius)={_format(report['effective_steer_from_physical_radius_deg'], 2)}deg "
            f"physical_radius(lap)={_format(report['physical_radius_from_lap_m'], 3)}m "
            f"effective_steer(lap)={_format(report['effective_steer_from_physical_lap_deg'], 2)}deg"
        )
        print(
            "  "
            f"has_feedback_speed={report['has_feedback_speed']} "
            f"has_feedback_steer={report['has_feedback_steer']} "
            f"has_imu_yaw={report['has_imu_yaw']} "
            f"has_pose={report['has_pose']}"
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
